# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix_prototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flix_prototype
	pod "AlamofireImage"

  target 'Flix_prototypeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flix_prototypeUITests' do
    # Pods for testing
  end

end
